### ISSUE TITLE
Same key for 2 different files

### ISSUE THREAD

**Issue by piercus** [drpicox/grunt-frontmatter#1]
Suppose i have the following structure

```
/foo/index.md
/bar/index.md
```

Then grunt-frontmatter is not able to handle it because it is using basename as key to the json object.

It would be good to be able to : 
- Output an array in the json
OR
- Use the full path name as the key in the json output

Thank you for your help

**Comment by drpicox** [comment]
I'll take a look to this usecase.

**Comment by drpicox** [comment]
Hi!

I have added a `dirname` configuration flag. 
If it is true it adds the `dirname` and uses it inside the key.

Check: https://github.com/drpicox/grunt-frontmatter/tree/master/examples/nested

**Comment by piercus** [comment]
Great thank you
